language: php

php:
  - 7.1
  - 7.2
  - 7.3

matrix:
  - COMPOSER_FLAGS=""
  - COMPOSER_FLAGS="--prefer-lowest"

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --prefer-dist --no-interaction --no-suggest $COMPOSER_FLAGS

script: vendor/bin/phpunit
